#!/usr/bin/env bash
# Configures Nginx server for redirection

# Install Nginx if not already installed
apt-get update
apt-get install -y nginx

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx for redirection
sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
