#!/usr/bin/env bash
# Configures Nginx server for redirection

# Install Nginx if not already installed
apt-get update
apt-get install -y nginx

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx for redirection
cat > /etc/nginx/sites-available/default << EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    location / {
        try_files \$uri \$uri/ =404;
    }
}
EOF

# Restart Nginx to apply changes
service nginx restart
