#!/usr/bin/env bash
# Configures Nginx server for redirection

# Install Nginx if not already installed
apt-get update
apt-get install -y nginx

# Create a simple HTML file
echo "Hello World!" > /var/www/html/index.html

# Configure Nginx for redirection
config_file="/etc/nginx/sites-available/default"
redirect_url="https://www.youtube.com/watch?v=QH2-TGUlwu4"

# Use sed to add the redirection configuration
sed -i '/server_name _;/a \
    location /redirect_me { \
        return 301 '"$redirect_url"'; \
    }' "$config_file"

# Test Nginx configuration
nginx -t

# Restart Nginx
service nginx restart
